service: newLambdaFunction
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

package:
  individually: true

functions:
  handler:
    handler: index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8008
    noPrependStageInUrl: true