service: newLambdaFunction
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  stage: prod

package:
  individually: true
  excludeDevDependencies: true

functions:
  handler:
    handler: src/index.handle
    events:
      - httpApi: '*'

plugins:
  - serverless-plugin-typescript
