/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Block: typeof import('./src/components/editor/Block.vue')['default']
    Button: typeof import('./src/components/forms/Button.vue')['default']
    CommandPalette: typeof import('./src/components/command-palette/CommandPalette.vue')['default']
    EditorSkeleton: typeof import('./src/components/skeletons/EditorSkeleton.vue')['default']
    MilkdownEditor: typeof import('./src/components/editor/MilkdownEditor.vue')['default']
    Modal: typeof import('./src/components/modal/Modal.vue')['default']
    Navbar: typeof import('./src/components/navbar/Navbar.vue')['default']
    NotesList: typeof import('./src/components/notes-list/NotesList.vue')['default']
    Pagination: typeof import('./src/components/pagination/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/components/sidebar/SidebarItem.vue')['default']
    Slash: typeof import('./src/components/editor/Slash.vue')['default']
    Spinner: typeof import('./src/components/spinner/Spinner.vue')['default']
    TextInput: typeof import('./src/components/forms/TextInput.vue')['default']
  }
}
