/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddNote: typeof import('./src/components/add-note/AddNote.vue')['default']
    CardItem: typeof import('./src/components/view-detail/CardItem.vue')['default']
    ItemList: typeof import('./src/components/view-detail/ItemList.vue')['default']
    MilkdownEditor: typeof import('./src/components/editor/MilkdownEditor.vue')['default']
    Navbar: typeof import('./src/components/navbar/Navbar.vue')['default']
    NotesList: typeof import('./src/components/notes-list/NotesList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    Spinner: typeof import('./src/components/spinner/Spinner.vue')['default']
    ViewDetail: typeof import('./src/components/view-detail/ViewDetail.vue')['default']
  }
}
